### PR TITLE
hopfix; fix relative path issue

### PR DESCRIPTION
**Pull request by lukszy**
Quick fix for relative path issue. Hope it will help

Cheers!

### CODE REVIEW

**Comment by ragingwind** [comment]
Could you make it clean? Please don't mess up indent to own style

**Comment by lukszy** [comment]
Fixed; Hope this helps. If you notice any bug, please let me know

**Comment by ragingwind** [comment]
It's transform stream plugin. We don't need to add actual path where to write. Why do you want to add relative path for? also test case is missing.

**Comment by ragingwind** [comment]
I close the issue due to inactivity. Feel free to reopen If you need to

**Pull request closed without merging**
